### ISSUE TITLE
How to run a program in the background (&) and how to removes the job from the shell's job list (disown)?

### ISSUE THREAD

**Issue by ram535** [bsutton/dshell#39] opened 2020-01-14 06:57 UTC
For example:

```
okular & disown
```

It would launch okular in the background and detached from the terminal. The terminal is free to type other commands and also  if I close the terminal the program keeps running.

**Comment by bsutton** [comment] 2020-01-14 08:09
I'm looking implement a start method which would allow you to start a process and continue executing.

**Comment by bsutton** [comment] 2020-01-14 11:16
I would be interested in your input on the best syntax to implement this.

It would appear that we need to methods.

'someprocess'.detached

The above command would start the process and then full detach the child process.
We could perhaps return a pid so the parent could terminate it at a later date.
I would assume as the child process is detached its output wouldn't been seen on the console.

'someprocess'.start

The above command would start the process and return immediately.
As this variation wouldn't be fully detached I would assume that its output would be visible on the console.
If the child is outputing data even in this detached state it seems to me that we should still be able to process its output. I'm not certain what the correct way is to handle the output given its happening asynchronously to the rest of the script.
If we used  forEach rather than start we could process the output as it would be entering the forEach on a callback. The forEach would need a 'runInBackground' option or similar.

This needs quite a bit of thought and some experimenation which is why I've not done it so far.

It would probably be easier to do the detached version and initially return a void which would could change at a later date to return a pid or similar without breaking the api.

Thoughts?

Would the detached option be sufficient for your requirement at this stage?

**Comment by ram535** [comment] 2020-01-14 22:26
`'someprocess'.detached` this gives me a pretty would I idea of what it is doing. But `'someprocess'.start` is not really clear just by reading it. I think a lot people would ask what is the different between `'someprocess'.start` and `'someprocess'.run`. I think something like `'someprocess'.backGround` makes it clear what is the intention.

> As this variation wouldn't be fully detached I would assume that its output would be visible on the console.
If the child is outputing data even in this detached state it seems to me that we should still be able to process its output.

I agree.

> If we used forEach rather than start we could process the output as it would be entering the forEach on a callback. The forEach would need a 'runInBackground' option or similar.

I think I see your point here but be able to just `'someprocess'.backGround` looks kind of elegant, don't you think? or `'someprocess'.backGround(do something with the output)`.
 

> It would probably be easier to do the detached version and initially return a void which would could change at a later date to return a pid or similar without breaking the api.

I think this would be a good first step to all these features.

> Would the detached option be sufficient for your requirement at this stage?

yes

**Comment by bsutton** [comment] 2020-01-14 23:38
I've done some more work on this and I now don't think detached is a good idea.
The problem is combinational explosion.
We already have:
.run
.shell
and now we are looking to add .detached.

The problem is that when detaching you may also need to run the child in a shell. So you end up needing four variants.

For the moment I've gone down the path of .start with two named args.
void start({runInshell = false, detached=false);

I've improved the doco on start and run to help a user choose the correct method.

This gives the user control over the full four combination with one entry point.
I think we should leave .run as its a nice convenience method for what is likely to be the most common scenario.
I've marked .shell as deprecated.

We still have the option of adding a return type to start which would then give a user control over the child process.

**Comment by bsutton** [comment] 2020-01-15 11:24
I'm going to close this issue as I think we have dealt with the core requirement.
If you still think we need a way to manage jobs then feel free to open another issue. At this point I'm inclined to allow users to use the existing tools to do this.

**Closed by bsutton** 2020-01-15 11:24 UTC
